name = "kumackey-com"
compatibility_date = "2024-09-23"
routes = [
  { pattern = "kumackey.com/*", zone_name = "kumackey.com" },
  { pattern = "www.kumackey.com/*", zone_name = "kumackey.com" }
]

[assets]
directory = "./"
