name = "kumackey-com"
compatibility_date = "2024-09-23"

[[routes]]
pattern = "kumackey.com"
custom_domain = true

[[routes]]
pattern = "www.kumackey.com"
custom_domain = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
